services:

  postgres:
    image: postgres:16
    container_name: cloudcart-postgres
    environment:
      POSTGRES_USER: cloudcart
      POSTGRES_PASSWORD: cloudcart
      POSTGRES_DB: cloudcart
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user-service:
    build: ./user-service
    container_name: cloudcart-user
    ports:
      - "5001:5001"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: cloudcart
      DB_USER: cloudcart
      DB_PASSWORD: cloudcart
    depends_on:
      - postgres

  product-service:
    build: ./product-service
    container_name: cloudcart-product
    ports:
      - "5002:5002"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: cloudcart
      DB_USER: cloudcart
      DB_PASSWORD: cloudcart
    depends_on:
      - postgres

  order-service:
    build: ./order-service
    container_name: cloudcart-order
    ports:
      - "5003:5003"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: cloudcart
      DB_USER: cloudcart
      DB_PASSWORD: cloudcart
    depends_on:
      - postgres

  api-gateway:
    build: ./api-gateway
    container_name: cloudcart-gateway
    ports:
      - "5000:5000"
    depends_on:
      - user-service
      - product-service
      - order-service

  payment-service:
    build: ./payment-service
    container_name: cloudcart-payment
    ports:
      - "5004:5004"

  notification-service:
    build: ./notification-service
    container_name: cloudcart-notification
    ports:
      - "5005:5005"

  redis:
    image: redis:7-alpine
    container_name: cloudcart-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: cloudcart-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:
