apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudcart-config
  namespace: {{ .Values.namespace }}
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: cloudcart
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
