namespace: cloudcart

images:
  apiGateway: ghcr.io/asthak-2505/cloudcart-api-gateway
  userService: ghcr.io/asthak-2505/cloudcart-user-service
  productService: ghcr.io/asthak-2505/cloudcart-product-service
  orderService: ghcr.io/asthak-2505/cloudcart-order-service
  paymentService: ghcr.io/asthak-2505/cloudcart-payment-service
  notificationService: ghcr.io/asthak-2505/cloudcart-notification-service

tag: latest

replicas:
  apiGateway: 2
  userService: 1
  productService: 1
  orderService: 1
  paymentService: 1
  notificationService: 1

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  cpuTarget: 70
